---
id: Stream_Wrapper
name: Stream_Wrapper
full: PHP stream wrappers library
description: A library of stream wrappers.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Stream_Wrapper
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha5
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7.4 || ^8
  dev:
    composer:
      horde/log: ^3
      horde/test: ^3
  optional:
    composer:
      horde/log: ^3
